// <auto-generated />
using System;
using BankNetworkIntelligence.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankNetworkIntelligence.Core.Migrations
{
    [DbContext(typeof(BankNetworkDbContext))]
    partial class BankNetworkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.Bank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("banks", (string)null);
                });

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.BankLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankId")
                        .HasColumnType("integer");

                    b.Property<string>("HebicCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LocationKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.HasIndex("LocationKey")
                        .IsUnique();

                    b.ToTable("bank_locations", (string)null);
                });

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.HebicImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Period")
                        .IsUnique();

                    b.ToTable("hebic_imports", (string)null);
                });

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.LocationSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasAps")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasAtm")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasBranch")
                        .HasColumnType("boolean");

                    b.Property<int>("ImportId")
                        .HasColumnType("integer");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("LocationId", "ImportId")
                        .IsUnique();

                    b.ToTable("location_snapshots", (string)null);
                });

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Prefecture")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Prefecture")
                        .IsUnique();

                    b.ToTable("municipalities", (string)null);
                });

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.BankLocation", b =>
                {
                    b.HasOne("BankNetworkIntelligence.Core.Models.Bank", "Bank")
                        .WithMany("Locations")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.LocationSnapshot", b =>
                {
                    b.HasOne("BankNetworkIntelligence.Core.Models.HebicImport", "Import")
                        .WithMany("LocationSnapshots")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankNetworkIntelligence.Core.Models.BankLocation", "Location")
                        .WithMany("Snapshots")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankNetworkIntelligence.Core.Models.Municipality", "Municipality")
                        .WithMany("LocationSnapshots")
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Import");

                    b.Navigation("Location");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.Bank", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.BankLocation", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.HebicImport", b =>
                {
                    b.Navigation("LocationSnapshots");
                });

            modelBuilder.Entity("BankNetworkIntelligence.Core.Models.Municipality", b =>
                {
                    b.Navigation("LocationSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
